### ISSUE TITLE
function[1]

### ISSUE THREAD

**Issue by akhialomgir** [Salenzo/salenzo.github.io#10]
```console
Please choose your operation:
[1] Preview
[2] Upload
[3] Only generate without previewing or uploading
[4] Start writing a blog post
[0] Exit
发生了一些事情。（Something happened.）
No such file or directory @ rb_sysopen - .git/HEAD
C:/Users/akhia/Documents/salenzo.github.io/slzblog.rb:17:in `read'
C:/Users/akhia/Documents/salenzo.github.io/slzblog.rb:17:in `generate'
C:/Users/akhia/Documents/salenzo.github.io/slzblog.rb:96:in `interface'
C:/Users/akhia/Documents/salenzo.github.io/slzblog.rb:145:in `<main>'
按任意键退出……
```

**Comment by satgo1546** [comment]
This is, of course, a typical (if not bad) first issue.

**Comment by satgo1546** [comment]
我尝试了几种可能的错误，仍然不知道这是为什么。你能把如何运行slzblog.rb的详细情况描述一下吗？这包括如何启动（在终端或资源管理器）和该脚本附近文件的情况等。

**Comment by satgo1546** [comment]
通过想象不存在的错误，修好了。
