### ISSUE TITLE
function[2]

### ISSUE THREAD

**Issue by akhialomgir** [Salenzo/salenzo.github.io#11]
```console
slzblog是将使用Markdown、SASS、HTML模板技术制作的网站生成为浏览器可以直接查看的网页文件集的工具。注意，本工具与博客并无直接
关系。
请选择你的英雄：
[1] 预览
[2] 上传
[3] 只生成而不预览或上传
[4] 开始编写一篇博客文章
[0] 退出

Please choose your operation:
[1] Preview
[2] Upload
[3] Only generate without previewing or uploading
[4] Start writing a blog post
[0] Exit
正在编译样式表src/assets/css/main.scss……
发生了一些事情。（Something happened.）
用SASS对src/assets/css/main.scss处理失败了！
slzblog.rb:35:in `block in generate'
slzblog.rb:21:in `each'
slzblog.rb:21:in `generate'
slzblog.rb:96:in `interface'
slzblog.rb:145:in `<main>'
按任意键退出……
```

**Comment by satgo1546** [comment]
Install SASS:
```bash
npm install -g sass
```
